hyper_parameter:
  learning_rate: 1.0e-4  # 1e-4 -> 1.0e-4 for float representation
  ratio_ssi: 1
  ratio_tgm: 10
  epochs: 50
  patient: 5
  batch_size: 1
  conv_out_channel: 64
  conv: true